name: Deploy to prd

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'NO_NEED_TO_DOUBLE_CHECK') }}
    uses: ./.github/workflows/deploy.yml
