name: Deploy to prd

on:
  push:
    branches:
      - main
    tags-ignore:
      - NO_NEED_TO_DOUBLE_CHECK

jobs:
  check_1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJson(github.event.pull_request.labels.*.name) }}
      - run: echo ${GITHUB_REF##*/}
      - run: echo ${{ github.ref }}
      
  check_2:
    uses: ./.github/workflows/check.yml

  deploy:
    if: ${{ !startsWith(github.ref, 'refs/tags/NO_NEED_TO_DOUBLE_CHECK') }}
    uses: ./.github/workflows/deploy.yml
    with:
      env_with_suffix: prd
