name: Deploy to prd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      env_with_suffix: prd
