name: Deploy to prd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          x=${{ toJson(github.event.pull_request.labels.*.name) }}

  test:
    uses: ./.github/workflows/test.yml

  deploy:
    if: contains(github.event.pull_request.labels.*.name, 'NO_NEED_TO_DOUBLE_CHECK')
    uses: ./.github/workflows/deploy.yml
    with:
      env_with_suffix: prd
