name: Deploy to prd

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      check_pr_labels_result: ${{ steps.check_pr_labels_result.outputs.boolean }}
      test: ${{ steps.test.outputs.test }}
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: Check PR labels action step
        id: check_pr_labels
        uses: shioyang/check-pr-labels-on-push-action@v1.0.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["NO_NEED_TO_DOUBLE_CHECK"]'
        timeout-minutes: 5
      - name: See result
        id: check_pr_labels_result
        run: echo "boolean=${{ steps.check_pr_labels.outputs.result }}" >> "$GITHUB_OUTPUT"
      - name: Test
        id: test
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - name: step1
        id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"

  check2:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.check.outputs.check_pr_labels_result }}
      - run: echo ${{ needs.check.outputs.test }}
  
  deploy:
    needs: check
    if: ${{ needs.check.outputs.check_pr_labels_result.boolean }} == 'false'
    uses: ./.github/workflows/deploy.yml
    with:
      env_with_suffix: prd
