name: Deploy to prd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJson(github.event.pull_request.labels.*.name) }}
      - run: echo ${GITHUB_REF##*/}
      - run: echo ${{ github.ref }}
      
  check_2:
    uses: ./.github/workflows/check.yml

  deploy:
    if: ${{ !contains(github.ref, 'refs/tags/NO_NEED_TO_DOUBLE_CHECK') }}
    uses: ./.github/workflows/deploy.yml
    with:
      env_with_suffix: prd
