name: Deploy to prd

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      check_pr_labels_result: ${{ steps.check_pr_labels_result.outputs.status }}
    steps:
      - name: Check PR labels action step
        id: check_pr_labels
        uses: shioyang/check-pr-labels-on-push-action@v1.0.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["NO_NEED_TO_DOUBLE_CHECK"]'
        timeout-minutes: 5
      - name: See result
        id: check_pr_labels_result
        run: echo "${{ steps.check_pr_labels.outputs.result }}"

  check2:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.check.outputs.check_pr_labels_result }}

  deploy:
    needs: check
    if : ${{ needs.check.outputs.check_pr_labels_result }} == 'false'
    uses: ./.github/workflows/deploy.yml
    with:
      env_with_suffix: prd
