name: test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check labels
        run: |
          echo ${{ toJson(github.event.pull_request.labels.*.name) }}

      - name: Check NO_NEED_TO_DOUBLE_CHECK label
        if: contains(github.event.pull_request.labels.*.name, 'NO_NEED_TO_DOUBLE_CHECK')      
        run: |
          echo "NO_NEED_TO_DOUBLE_CHECK is labeled"
